import GlobalState from '@/context'
import type { Metadata } from 'next'
import { Raleway} from 'next/font/google'
import Header from "@/component/Header"
import Footer from "@/component/Footer"
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const Ral = Raleway({   weight:'400' ,subsets:['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={Ral.className} style={{margin:0,padding:0}}>
        <GlobalState>
          <Header/>
        {children}
        <Footer/>
        </GlobalState>
        <ToastContainer />
        </body>
    </html>
  )
}
